### ISSUE TITLE
Sleet posting getting delayed

### ISSUE THREAD

**Issue by LapysAoneeris** [outerspatialdev/sky-poster-bot#11]
**Describe the bug**
The bot is posting skeet on discord as expected, but with a long delay. Yesterday afternoon skeet got posted on discord this morning, and a skeet from this morning wasn’t yet pushed to discord. 

**To Reproduce**
1. Setup the bot on discord, it was working fine until yesterday 
2. Posted a skeet yesterday at 4:48 pm CET
3. The bot posted the notification on Discord today at 7:49 am

**Expected behavior**
I’m not expecting immediate repost of course, but being delayed by a few hours is a an issue when I’m using it as a way to notify that I’m going live on Twitch

**Additional context**
As I only had that happen since yesterday, I can’t check if it would be always the same delay (I’m waiting to see when this morning skeet will get reposted), but judging by the fact it is almost exactly 15h later, I would guess there might be timezone shenanigans happening?

**Comment by malooski** [comment]
I wonder if processing each firehose post is taking too long now that bsky activity has significantly increased.

**Comment by malooski** [comment]
Made some minor updates, I'll deploy them tomorrow so I can address if there are any issues

**Comment by LapysAoneeris** [comment]
I forgot to update, but it seems to be working fine now. With the wave of new users and the difficulties Bluesky encountered, I'm not surprised some tools broke. Thank for your hard work.
