### ISSUE TITLE
Bot is not linking to the right URL when posting an update on Discord

### ISSUE THREAD

**Issue by LapysAoneeris** [outerspatialdev/sky-poster-bot#14]
**Describe the bug**
When posting the embedded Discord message, the bot posts a link to a URL that isn't the one to the skeet, which leads to an error page on Bluesky. The first part of the link is alright, but the last part, with the id, is wrong (see screenshot of the expected link and the link in the message)

**To Reproduce**
1. Add the bot to Discord and set it up to post a message when a skeet is detected on an account
2. Post on Bluesky
3. The link with the text "Username skeeted." point to a wrong URL
4. Clicking on the link brings an error page. 

**Expected behavior**
Expected behaviour would be to have a link to the skeet, so anyone coming from Discord can get directly to the post instead of having to look through my history

**Screenshots**
![image](https://github.com/user-attachments/assets/4e1e9207-0ed7-47e1-9c9f-24487407a46d)

**Comment by malooski** [comment]
Fixed by 71e56c0f1f5174fc4b60375dbd17c317423ae24e

<img width="771" alt="Screenshot 2024-12-02 at 9 48 57 AM" src="https://github.com/user-attachments/assets/3025ba80-501b-4441-8b83-416f32a2b820">
